export const ADD_PLACE = "ADD_PLACE";
export type ADD_PLACE = typeof ADD_PLACE;

export const DELETE_PLACE = "DELETE_PLACE";
export type DELETE_PLACE = typeof DELETE_PLACE;

export const FETCH_ARRIVALS_REQUEST = "FETCH_ARRIVALS_REQUEST";
export type FETCH_ARRIVALS_REQUEST = typeof FETCH_ARRIVALS_REQUEST;

export const FETCH_ARRIVALS_FAILURE = "FETCH_ARRIVALS_FAILURE";
export type FETCH_ARRIVALS_FAILURE = typeof FETCH_ARRIVALS_FAILURE;

export const FETCH_ARRIVALS_SUCCESS = "FETCH_ARRIVALS_SUCCESS";
export type FETCH_ARRIVALS_SUCCESS = typeof FETCH_ARRIVALS_SUCCESS;

export const FETCH_STOPS_REQUEST = "FETCH_STOPS_REQUEST";
export type FETCH_STOPS_REQUEST = typeof FETCH_STOPS_REQUEST;

export const FETCH_STOPS_FAILURE = "FETCH_STOPS_FAILURE";
export type FETCH_STOPS_FAILURE = typeof FETCH_STOPS_FAILURE;

export const FETCH_STOPS_SUCCESS = "FETCH_STOPS_SUCCESS";
export type FETCH_STOPS_SUCCESS = typeof FETCH_STOPS_SUCCESS;

export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";
export type SET_SEARCH_PARAMS = typeof SET_SEARCH_PARAMS;
